import { 
  DrawingProject, 
  DrawingItem, 
  DrawingCompany,
  DrawingVariationOrder
} from '../types/drawings';

export const MOCK_COMPANIES: DrawingCompany[] = [
  {
    id: 'comp-hp',
    name: 'CÔNG TY TNHH THIẾT KẾ XÂY DỰNG & THƯƠNG MẠI HƯNG PHÁT',
    shortName: 'Hưng Phát (Tổng Thầu / Thiết Kế)',
    role: 'MAIN_CONTRACTOR',
    contactPerson: 'KTS. Lê Hoàng Sỹ',
    phone: '0908 123 456',
  },
  {
    id: 'comp-cdt-01',
    name: 'CÔNG TY CỔ PHẦN ĐẦU TƯ ĐỊA ỐC TÂN PHÚ',
    shortName: 'CĐT Địa Ốc Tân Phú',
    role: 'INVESTOR',
    contactPerson: 'Ông Trần Minh Thắng',
    phone: '0912 345 678',
  },
  {
    id: 'comp-sub-glass',
    name: 'CÔNG TY TNHH NHÔM KÍNH & MẶT DỰNG TOÀN CẦU',
    shortName: 'Thầu Phụ Nhôm Kính Toàn Cầu',
    role: 'SUB_CONTRACTOR',
    contactPerson: 'KS. Trịnh Văn Lâm',
    phone: '0933 555 789',
  },
  {
    id: 'comp-sub-mep',
    name: 'CÔNG TY CP CƠ ĐIỆN LẠNH NAM Á',
    shortName: 'Thầu Phụ Cơ Điện Nam Á',
    role: 'SUB_CONTRACTOR',
    contactPerson: 'KS. Nguyễn Bá Thành',
    phone: '0988 777 666',
  },
  {
    id: 'comp-tvgs',
    name: 'CÔNG TY TƯ VẤN THẨM TRA & GIÁM SÁT SÀI GÒN',
    shortName: 'Tư Vấn Giám Sát Sài Gòn (TVGS)',
    role: 'SUPERVISION_CONSULTANT',
    contactPerson: 'KS. Đặng Quốc Bảo',
    phone: '0903 999 888',
  },
];

export const MOCK_PROJECTS: DrawingProject[] = [
  {
    id: 'proj-01',
    projectCode: 'CT-2026-HP01',
    projectName: 'Biệt Thự Phố Hiện Đại - Tân Phú',
    investorId: 'comp-cdt-01',
    investorName: 'Cty CP Địa Ốc Tân Phú (Đại diện: Ông Trần Minh Thắng)',
    mainContractorId: 'comp-hp',
    mainContractorName: 'Cty TNHH Thiết Kế Xây Dựng Hưng Phát',
    address: '153G Lũy Bán Bích, P. Tân Thới Hòa, Q. Tân Phú, TP. HCM',
    contractValue: 4500000000,
    startDate: '2026-01-15',
    expectedEndDate: '2026-09-30',
    status: 'CONSTRUCTING',
    leadArchitect: 'KTS. Lê Hoàng Sỹ',
    leadEngineer: 'KS. Võ Huy Phong',
    drawingCount: 32,
  },
  {
    id: 'proj-02',
    projectCode: 'CT-2026-HP02',
    projectName: 'Nhà Phố 4 Tầng Kết Cấu Thép - Bình Tân',
    investorId: 'comp-cdt-01',
    investorName: 'Bà Ngô Thị Bích Ngọc',
    mainContractorId: 'comp-hp',
    mainContractorName: 'Cty TNHH Thiết Kế Xây Dựng Hưng Phát',
    address: '88 Đường số 7, P. An Lạc A, Q. Bình Tân, TP. HCM',
    contractValue: 2800000000,
    startDate: '2026-03-01',
    expectedEndDate: '2026-11-15',
    status: 'DESIGNING',
    leadArchitect: 'KTS. Nguyễn Nguyên Hùng',
    leadEngineer: 'KS. Ngô Tiến Đạt',
    drawingCount: 16,
  },
];

export const MOCK_DRAWINGS: DrawingItem[] = [
  // 1. Bản vẽ Kiến Trúc - BẢN SỬA ĐỔI (REVISION_MODIFIED)
  {
    id: 'draw-01',
    projectId: 'proj-01',
    companyId: 'comp-hp',
    companyName: 'Hưng Phát (Tổng Thầu / Thiết Kế)',
    drawingNumber: 'KT-01',
    title: 'Mặt Bằng Định Vị & Kiến Trúc Tầng 1 (Chỉnh Sửa Mở Rộng Sảnh)',
    discipline: 'ARCHITECTURE',
    stageType: 'CONSTRUCTION',
    issueNature: 'REVISION_MODIFIED',
    scale: '1/100',
    sheetSize: 'A2',
    currentRevision: 'Rev 02',
    status: 'APPROVED_FOR_CONSTRUCTION',
    author: 'KTS. Lê Hoàng Sỹ',
    approver: 'TVGS Đặng Quốc Bảo',
    approvedDate: '2026-02-10',
    fileUrl: '#',
    tags: ['Mặt bằng', 'Tầng 1', 'Bản vẽ sửa đổi', 'Đã duyệt thi công'],
    revisions: [
      {
        id: 'rev-01-0',
        drawingId: 'draw-01',
        revisionNumber: 'Rev 00',
        issueNature: 'NEW_ISSUE',
        changeDate: '2026-01-18',
        changedBy: 'KTS. Lê Hoàng Sỹ',
        issuingCompany: 'Hưng Phát',
        changeReasonCategory: 'INVESTOR_REQUEST',
        changeDescription: 'Phát hành bản vẽ sơ bộ lần đầu lấy ý kiến Chủ Đầu Tư',
        fileUrl: '#',
        isCurrent: false,
      },
      {
        id: 'rev-01-1',
        drawingId: 'draw-01',
        revisionNumber: 'Rev 01',
        issueNature: 'REVISION_MODIFIED',
        changeDate: '2026-01-28',
        changedBy: 'KTS. Lê Hoàng Sỹ',
        issuingCompany: 'Hưng Phát',
        changeReasonCategory: 'INVESTOR_REQUEST',
        changeDescription: 'Mở rộng sảnh phụ thêm 800mm và điều chỉnh hướng mở cửa gara theo phong thủy',
        approvedBy: 'Ông Trần Minh Thắng (CĐT)',
        approvedDate: '2026-01-29',
        fileUrl: '#',
        isCurrent: false,
      },
      {
        id: 'rev-01-2',
        drawingId: 'draw-01',
        revisionNumber: 'Rev 02',
        issueNature: 'REVISION_MODIFIED',
        changeDate: '2026-02-10',
        changedBy: 'KTS. Lê Hoàng Sỹ',
        issuingCompany: 'Hưng Phát',
        changeReasonCategory: 'SITE_CONFLICT',
        changeDescription: 'Khớp nối vị trí cột kết cấu C1-C3 và phát hành thi công chính thức (AFC)',
        approvedBy: 'TVGS Đặng Quốc Bảo',
        approvedDate: '2026-02-10',
        fileUrl: '#',
        isCurrent: true,
      },
    ],
    costingLinkId: 'BOM-KT01-T1',
    createdAt: '2026-01-18T08:00:00Z',
    updatedAt: '2026-02-10T14:30:00Z',
  },

  // 2. Bản vẽ Kết Cấu - BẢN VẼ PHÁT SINH HIỆN TRƯỜNG (VARIATION_ORDER)
  {
    id: 'draw-02',
    projectId: 'proj-01',
    companyId: 'comp-hp',
    companyName: 'Hưng Phát (Tổng Thầu / Thiết Kế)',
    drawingNumber: 'KC-PS-01',
    title: 'Gia Cường Bổ Sung Dầm Phụ D2A & Đổi Thép Móng Do Đất Yếu',
    discipline: 'STRUCTURE',
    stageType: 'VARIATION_SITE',
    issueNature: 'VARIATION_ORDER',
    scale: '1/25',
    sheetSize: 'A1',
    currentRevision: 'Rev 01',
    status: 'APPROVED_FOR_CONSTRUCTION',
    author: 'KS. Võ Huy Phong',
    approver: 'CĐT & TVGS Sài Gòn',
    approvedDate: '2026-02-18',
    fileUrl: '#',
    tags: ['Phát sinh', 'Gia cường dầm', 'Đất yếu', 'Tăng chi phí'],
    isVariationOrder: true,
    variationAmount: 45000000, // Phát sinh tăng 45 triệu
    revisions: [
      {
        id: 'rev-02-1',
        drawingId: 'draw-02',
        revisionNumber: 'Rev 01',
        issueNature: 'VARIATION_ORDER',
        changeDate: '2026-02-18',
        changedBy: 'KS. Võ Huy Phong',
        issuingCompany: 'Hưng Phát',
        changeReasonCategory: 'SITE_CONFLICT',
        changeDescription: 'Địa chất lớp bùn dày hơn khảo sát: Tăng thép đài móng M1 từ D16 lên D18, bổ sung dầm giằng phụ D2A nhịp 4.2m (+45.000.000 đ)',
        approvedBy: 'Trần Minh Thắng (CĐT)',
        approvedDate: '2026-02-19',
        fileUrl: '#',
        isCurrent: true,
      },
    ],
    costingLinkId: 'BOM-KC-PS01',
    createdAt: '2026-02-18T10:00:00Z',
    updatedAt: '2026-02-19T16:00:00Z',
  },

  // 3. Bản vẽ MỚI PHÁT HÀNH TỪ THẦU PHỤ NHÔM KÍNH (NEW_ISSUE - SHOP DRAWING)
  {
    id: 'draw-03',
    projectId: 'proj-01',
    companyId: 'comp-sub-glass',
    companyName: 'Thầu Phụ Nhôm Kính Toàn Cầu',
    drawingNumber: 'SHOP-NK-01',
    title: 'Shop Drawing Chi Tiết Cắt Nhôm Xingfa & Vách Kính Cường Lực Mặt Tiền',
    discipline: 'ARCHITECTURE',
    stageType: 'SHOP_DRAWING',
    issueNature: 'NEW_ISSUE',
    scale: '1/20',
    sheetSize: 'A1',
    currentRevision: 'Rev 00',
    status: 'PENDING_INVESTOR_APPROVAL',
    author: 'KS. Trịnh Văn Lâm (Toàn Cầu)',
    fileUrl: '#',
    tags: ['Shop Drawing', 'Nhôm Xingfa', 'Kính 12mm', 'Mặt tiền', 'Thầu phụ'],
    revisions: [
      {
        id: 'rev-03-0',
        drawingId: 'draw-03',
        revisionNumber: 'Rev 00',
        issueNature: 'NEW_ISSUE',
        changeDate: '2026-02-22',
        changedBy: 'KS. Trịnh Văn Lâm',
        issuingCompany: 'Nhôm Kính Toàn Cầu',
        changeReasonCategory: 'INVESTOR_REQUEST',
        changeDescription: 'Đệ trình phương án Shop Drawing mặt dựng nhôm kính Xingfa Class A kèm chi tiết bản lề sàn Kinlong',
        fileUrl: '#',
        isCurrent: true,
      },
    ],
    costingLinkId: 'BOM-SHOP-NK01',
    createdAt: '2026-02-22T09:00:00Z',
    updatedAt: '2026-02-22T09:00:00Z',
  },

  // 4. Bản vẽ Điện Nước TỪ THẦU PHỤ NAM Á - BẢN SỬA ĐỔI REDLINE (REDLINE_MARKUP)
  {
    id: 'draw-04',
    projectId: 'proj-01',
    companyId: 'comp-sub-mep',
    companyName: 'Thầu Phụ Cơ Điện Nam Á',
    drawingNumber: 'MEP-RL-02',
    title: 'Redline Điều Chỉnh Đường Ống Cấp Thoát Nước Tránh Xuyên Dầm D3',
    discipline: 'MEP',
    stageType: 'VARIATION_SITE',
    issueNature: 'REDLINE_MARKUP',
    scale: '1/50',
    sheetSize: 'A2',
    currentRevision: 'Rev 01',
    status: 'APPROVED_FOR_CONSTRUCTION',
    author: 'KS. Nguyễn Bá Thành (Nam Á)',
    approver: 'KS. Võ Huy Phong (Hưng Phát)',
    approvedDate: '2026-02-24',
    fileUrl: '#',
    tags: ['Redline', 'Hiện trường', 'Ống xuyên dầm', 'MEP'],
    revisions: [
      {
        id: 'rev-04-1',
        drawingId: 'draw-04',
        revisionNumber: 'Rev 01',
        issueNature: 'REDLINE_MARKUP',
        changeDate: '2026-02-24',
        changedBy: 'KS. Nguyễn Bá Thành',
        issuingCompany: 'Cơ Điện Nam Á',
        changeReasonCategory: 'SITE_CONFLICT',
        changeDescription: 'Vướng cốt thép dầm chính D3: Bẻ cong ống thoát D90 đi luồn dưới sàn âm thay vì đục xuyên dầm',
        approvedBy: 'KS. Võ Huy Phong (Hưng Phát)',
        approvedDate: '2026-02-24',
        fileUrl: '#',
        isCurrent: true,
      },
    ],
    costingLinkId: 'BOM-MEP-RL02',
    createdAt: '2026-02-24T14:00:00Z',
    updatedAt: '2026-02-24T17:00:00Z',
  },

  // 5. Bản vẽ XIN PHÉP XÂY DỰNG (PERMIT)
  {
    id: 'draw-05',
    projectId: 'proj-01',
    companyId: 'comp-hp',
    companyName: 'Hưng Phát (Tổng Thầu / Thiết Kế)',
    drawingNumber: 'XPXD-01',
    title: 'Hồ Sơ Bản Vẽ Xin Phép Xây Dựng Đã Được Quận Tân Phú Cấp Giấy Phép',
    discipline: 'ARCHITECTURE',
    stageType: 'PERMIT',
    issueNature: 'NEW_ISSUE',
    scale: '1/100',
    sheetSize: 'A0',
    currentRevision: 'Rev Final',
    status: 'APPROVED_FOR_CONSTRUCTION',
    author: 'KTS. Lê Chí Thân',
    approver: 'UBND Quận Tân Phú (GPXD Số 123/GPXD)',
    approvedDate: '2026-01-10',
    fileUrl: '#',
    tags: ['GPXD', 'Xin phép', 'Pháp lý', 'UBND Quận'],
    revisions: [
      {
        id: 'rev-05-0',
        drawingId: 'draw-05',
        revisionNumber: 'Rev Final',
        issueNature: 'NEW_ISSUE',
        changeDate: '2026-01-10',
        changedBy: 'KTS. Lê Chí Thân',
        issuingCompany: 'Hưng Phát',
        changeReasonCategory: 'REGULATORY_CHANGE',
        changeDescription: 'Bản vẽ xin phép xây dựng chính thức theo Giấy phép xây dựng số 123/GPXD-UBND',
        approvedBy: 'UBND Q. Tân Phú',
        approvedDate: '2026-01-10',
        fileUrl: '#',
        isCurrent: true,
      },
    ],
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },

  // 6. Bản vẽ HOÀN CÔNG (AS_BUILT)
  {
    id: 'draw-06',
    projectId: 'proj-01',
    companyId: 'comp-hp',
    companyName: 'Hưng Phát (Tổng Thầu / Thiết Kế)',
    drawingNumber: 'HC-KC-01',
    title: 'Bản Vẽ Hoàn Công Phần Ngầm & Cọc Móng Thực Tế Sau Ép',
    discipline: 'AS_BUILT',
    stageType: 'AS_BUILT',
    issueNature: 'AS_BUILT_FINAL',
    scale: '1/50',
    sheetSize: 'A1',
    currentRevision: 'Rev Final',
    status: 'APPROVED_FOR_CONSTRUCTION',
    author: 'KS. Võ Huy Phong',
    approver: 'TVGS Sài Gòn & CĐT',
    approvedDate: '2026-02-28',
    fileUrl: '#',
    tags: ['Hoàn công', 'Phần ngầm', 'Nhật ký ép cọc', 'Quyết toán'],
    revisions: [
      {
        id: 'rev-06-0',
        drawingId: 'draw-06',
        revisionNumber: 'Rev Final',
        issueNature: 'AS_BUILT_FINAL',
        changeDate: '2026-02-28',
        changedBy: 'KS. Võ Huy Phong',
        issuingCompany: 'Hưng Phát',
        changeReasonCategory: 'SITE_CONFLICT',
        changeDescription: 'Hoàn công độ sâu chìm cọc thực tế (Tim cọc C1-C18 đạt Pmax = 65 tấn)',
        approvedBy: 'TVGS Đặng Quốc Bảo',
        approvedDate: '2026-02-28',
        fileUrl: '#',
        isCurrent: true,
      },
    ],
    costingLinkId: 'BOM-HC-MONG',
    createdAt: '2026-02-28T09:00:00Z',
    updatedAt: '2026-02-28T15:00:00Z',
  },
];

export const MOCK_VARIATION_ORDERS: DrawingVariationOrder[] = [
  {
    id: 'vo-01',
    voNumber: 'VO-HP01-001',
    projectId: 'proj-01',
    projectName: 'Biệt Thự Phố Hiện Đại - Tân Phú',
    title: 'Phát sinh xử lý vướng ống nước ngầm cũ & gia cố móng băng trục 3',
    issueDate: '2026-03-02',
    requestedBy: 'SITE_CONDITION',
    legalBasis: 'Biên bản xử lý hiện trường số 03/BB-HT ngày 01/03/2026 giữa CĐT, TVGS và Hưng Phát',
    reasonCategory: 'SITE_CONFLICT',
    items: [
      {
        drawingId: 'draw-03',
        drawingNumber: 'KC-PS01',
        title: 'Chi Tiết Bổ Sung Móng Băng Trục 3 Tránh Ống Nước Cũ',
        revision: 'Rev 00',
        nature: 'Bản vẽ phát sinh',
        description: 'Bổ sung giằng móng BTCT M300 đá 1x2, cốt thép CB400V tránh đường ống hiện trạng',
        amount: 25000000,
      }
    ],
    totalAmount: 25000000,
    vatRate: 8,
    vatAmount: 2000000,
    totalWithVat: 27000000,
    timeExtensionDays: 3,
    status: 'APPROVED',
    signedByInvestor: 'Ông Trần Minh Thắng (Chủ Đầu Tư)',
    signedByConsultant: 'KS. Đặng Quốc Bảo (TVGS Sài Gòn)',
    signedByContractor: 'KTS. Lê Hoàng Sỹ (GĐ Thiết Kế Hưng Phát)',
    approvedDate: '2026-03-05',
    notes: 'Đã ký biên bản 3 bên, chi phí được cộng dồn vào đợt thanh toán giai đoạn 2',
    createdAt: '2026-03-02T10:00:00Z',
    updatedAt: '2026-03-05T14:30:00Z',
  },
  {
    id: 'vo-02',
    voNumber: 'VO-HP01-002',
    projectId: 'proj-01',
    projectName: 'Biệt Thự Phố Hiện Đại - Tân Phú',
    title: 'Chủ đầu tư yêu cầu nâng cấp toàn bộ hệ nhôm Xingfa sang Nhôm Kính Eurowindow cao cấp',
    issueDate: '2026-04-10',
    requestedBy: 'INVESTOR',
    legalBasis: 'Thư yêu cầu thay đổi vật liệu của CĐT ngày 08/04/2026',
    reasonCategory: 'CLIENT_REQUEST',
    items: [
      {
        drawingId: 'draw-05',
        drawingNumber: 'SHOP-NK-01',
        title: 'Bản Vẽ Shop Cửa Nhôm Kính Mặt Tiền Tầng 1 & Tầng 2',
        revision: 'Rev 01',
        nature: 'Bản vẽ chỉnh sửa vật liệu',
        description: 'Thay đổi hệ profile nhôm rãnh C châu Âu cách âm, kính hộp 2 lớp 5+9A+5mm dán an toàn',
        amount: 45000000,
      }
    ],
    totalAmount: 45000000,
    vatRate: 8,
    vatAmount: 3600000,
    totalWithVat: 48600000,
    timeExtensionDays: 5,
    status: 'SUBMITTED',
    signedByInvestor: 'Chờ CĐT ký duyệt',
    signedByConsultant: 'KS. Đặng Quốc Bảo (TVGS)',
    signedByContractor: 'KTS. Lê Hoàng Sỹ (Hưng Phát)',
    notes: 'Đã trình phụ lục hợp đồng, chờ CĐT hoàn tất ký duyệt',
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-04-10T16:00:00Z',
  }
];
